{% set name = "video-sorter" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/video-sorter-{{ version }}.tar.gz
  sha256: b10e177672e6d568d950967edf47e088effb18f11f8c875ee7f445c0ccfc7ae3

build:
  entry_points:
    - blink-summary = vsorter.blink_summary:main
    - mkmp4 = vsorter.mkmp4:main
    - vsorter-fix-times = vsorter.fix_file_times:main
    - movie2gif = vsorter.movie2gif:main
    - version-copy = vsorter.version_copy:main
    - vsorter = vsorter.vsorter:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm >=3.4.3
    - wheel
    - pip
  run:
    - python >=3.9
    - flask
    - gunicorn
    - numpy
    - ja-webutils
    - psutil

test:
  imports:
    - video_sorter
  commands:
    - pip check
    - blink-summary --help
    - mkmp4 --help
    - vsorter-fix-times --help
    - movie2gif --help
    - version-copy --help
    - vsorter --help
  requires:
    - pip

about:
  home: https://github.com/areeda/video-sorter
  dev_url: https://github.com/areeda/video-sorter.git
  summary: A collection of small programs to work with lots of video files
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - areeda
